const LOCALSTORAGE_PREFIX = process.env.VUE_APP_LOCALSTORAGE_PREFIX || 'quizme'

export const LocalStorageConstants = {
  QUIZ_SESSION_KEY: `${LOCALSTORAGE_PREFIX}|QUIZ_SESSION`,
  LAST_QUIZ_SESSION_ID: `${LOCALSTORAGE_PREFIX}|LAST_QUIZ_SESSION_ID`
}

export const QuestionTypeConstants = {
  SINGLE_SELECTION: 'SINGLE_CHOICE',
  MULTIPLE_SELECTION: 'MULTIPLE_SELECTION'
}
