// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:94899eb0-53c5-4a4c-9d4f-0bd079d979e3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3aKnpoazl",
    "aws_user_pools_web_client_id": "7qsep0u5r1i5t1al96gu4oemni",
    "aws_appsync_graphqlEndpoint": "https://7bmk5xuzibdnhdpsgohectrayy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
