// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6ff51e18-3914-4e57-96a7-5e5efbdf58c2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hHFUVzyfQ",
    "aws_user_pools_web_client_id": "3v7nknjr0bkilj31rto0m2qkgr"
};


export default awsmobile;
